### ISSUE TITLE
189-4

### ISSUE THREAD

**Issue by SapneshNaik** [SapneshNaik/GIT-189#4]
Proin eget tortor risus. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur aliquet quam id dui posuere blandit.

Vivamus suscipit tortor eget felis porttitor volutpat. Cras ultricies ligula sed magna dictum porta. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.

Nulla quis lorem ut libero malesuada feugiat. Sed porttitor lectus nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.

Cras ultricies ligula sed magna dictum porta. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Proin eget tortor risus.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $45.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/189-4).
- If you would like to fasten the development of this issue, you can 'Add Funding'  [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/189-4).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $60.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/funder2">funder2</a>
Co-Funder Message: I would like to add funding to this

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $45.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/jigahoc201">jigahoc201</a>
Co-Funder Message: I would like to add funds as well

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $200.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/sb-q0wou4101231">sb-q0wou4101231</a>
Co-Funder Message: I would like to add funds as well

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a>, has started work on the bounty.**
<hr />

**Message:** I'm starting work on this


<a href='https://sandbox.app.gitcommits.com/issue/189-4'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $90.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/multicc">multicc</a>
Co-Funder Message: I would like to add funding to this

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont2'>cont2</a>, has started work on the bounty.**
<hr />

**Message:** I have started work on this


<a href='https://sandbox.app.gitcommits.com/issue/189-4'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont2'>cont2</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/funder4'>funder4</a>.**
<hr />

**Message:** Pull request has been approved, you will receive the payment shortly.


<a href='https://sandbox.app.gitcommits.com/issue/189-4'>Click Here to view more</a> on GitCommits Bounty detail page.
